---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - name: Handle Clickhouse distribution tasks
      block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.x86_64.rpm"
            dest: "./{{ item }}-{{ clickhouse_version }}.rpm"
            mode: '0644'
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
            dest: "./clickhouse-common-static-{{ clickhouse_version }}.rpm"
            mode: '0644'

    - name: Install clickhouse packages
      become: true
      ansible.builtin.yum:
        name:
          - clickhouse-common-static-{{ clickhouse_version }}.rpm
          - clickhouse-client-{{ clickhouse_version }}.rpm
          - clickhouse-server-{{ clickhouse_version }}.rpm
      notify: Start clickhouse service

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0

- name: Install Vector
  hosts: vector
  become: true
  vars:
    vector_version: "0.33.1"
    vector_config_template: "vector.toml.j2"
    vector_config: "/etc/vector/vector.toml"

  tasks:
    - name: Update the package list
      ansible.builtin.apt:
        update_cache: true

    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - curl
        state: present

    - name: Download Vector .deb package
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
        dest: "/tmp/vector_{{ vector_version }}-1_amd64.deb"
        mode: '0644'

    - name: Install Vector .deb package
      ansible.builtin.apt:
        deb: "/tmp/vector_{{ vector_version }}-1_amd64.deb"

    - name: Check Vector version
      ansible.builtin.command: vector --version
      register: vector_version_output
      changed_when: false

    # - name: Remove downloaded .deb file
    #   ansible.builtin.file:
    #     path: "/tmp/vector_{{ vector_version }}-1_amd64.deb"
    #     state: absent

    - name: Show Vector version
      ansible.builtin.debug:
        var: vector_version_output.stdout_lines

    - name: Create Vector configuration file from template
      ansible.builtin.template:
        src: "{{ vector_config_template }}"
        dest: "{{ vector_config }}"
        owner: root
        group: root
        mode: '0644'
